apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: nginx-ingress-hc-config
spec:
  healthCheck:
    checkIntervalSec: 15
    port: 80
    type: HTTP
    requestPath: /healthz